// Code generated by MockGen. DO NOT EDIT.
// Source: event_publisher.go
//
// Generated by this command:
//
//	mockgen -source=event_publisher.go -destination=mocks/mock_event_publisher.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/iPatrushevSergey/gophprofile/app/internal/server/avatar/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockEventPublisher is a mock of EventPublisher interface.
type MockEventPublisher struct {
	ctrl     *gomock.Controller
	recorder *MockEventPublisherMockRecorder
	isgomock struct{}
}

// MockEventPublisherMockRecorder is the mock recorder for MockEventPublisher.
type MockEventPublisherMockRecorder struct {
	mock *MockEventPublisher
}

// NewMockEventPublisher creates a new mock instance.
func NewMockEventPublisher(ctrl *gomock.Controller) *MockEventPublisher {
	mock := &MockEventPublisher{ctrl: ctrl}
	mock.recorder = &MockEventPublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventPublisher) EXPECT() *MockEventPublisherMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockEventPublisher) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockEventPublisherMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockEventPublisher)(nil).Ping), ctx)
}

// PublishAvatarDeleted mocks base method.
func (m *MockEventPublisher) PublishAvatarDeleted(ctx context.Context, event dto.AvatarDeletedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAvatarDeleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAvatarDeleted indicates an expected call of PublishAvatarDeleted.
func (mr *MockEventPublisherMockRecorder) PublishAvatarDeleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAvatarDeleted", reflect.TypeOf((*MockEventPublisher)(nil).PublishAvatarDeleted), ctx, event)
}

// PublishAvatarUploaded mocks base method.
func (m *MockEventPublisher) PublishAvatarUploaded(ctx context.Context, event dto.AvatarUploadedEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishAvatarUploaded", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishAvatarUploaded indicates an expected call of PublishAvatarUploaded.
func (mr *MockEventPublisherMockRecorder) PublishAvatarUploaded(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishAvatarUploaded", reflect.TypeOf((*MockEventPublisher)(nil).PublishAvatarUploaded), ctx, event)
}
