// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/server/avatar/application/port/avatar_repository.go
//
// Generated by this command:
//
//	mockgen -source=app/internal/server/avatar/application/port/avatar_repository.go -destination=app/internal/server/avatar/application/port/mocks/mock_avatar_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/iPatrushevSergey/gophprofile/app/internal/server/avatar/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarReader is a mock of AvatarReader interface.
type MockAvatarReader struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarReaderMockRecorder
	isgomock struct{}
}

// MockAvatarReaderMockRecorder is the mock recorder for MockAvatarReader.
type MockAvatarReaderMockRecorder struct {
	mock *MockAvatarReader
}

// NewMockAvatarReader creates a new mock instance.
func NewMockAvatarReader(ctrl *gomock.Controller) *MockAvatarReader {
	mock := &MockAvatarReader{ctrl: ctrl}
	mock.recorder = &MockAvatarReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarReader) EXPECT() *MockAvatarReaderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockAvatarReader) FindByID(ctx context.Context, id string) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAvatarReaderMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAvatarReader)(nil).FindByID), ctx, id)
}

// ListByUserID mocks base method.
func (m *MockAvatarReader) ListByUserID(ctx context.Context, userID string) ([]entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAvatarReaderMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAvatarReader)(nil).ListByUserID), ctx, userID)
}

// ListExpiredUploading mocks base method.
func (m *MockAvatarReader) ListExpiredUploading(ctx context.Context, before time.Time) ([]entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredUploading", ctx, before)
	ret0, _ := ret[0].([]entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredUploading indicates an expected call of ListExpiredUploading.
func (mr *MockAvatarReaderMockRecorder) ListExpiredUploading(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredUploading", reflect.TypeOf((*MockAvatarReader)(nil).ListExpiredUploading), ctx, before)
}

// Ping mocks base method.
func (m *MockAvatarReader) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAvatarReaderMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAvatarReader)(nil).Ping), ctx)
}

// MockAvatarWriter is a mock of AvatarWriter interface.
type MockAvatarWriter struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarWriterMockRecorder
	isgomock struct{}
}

// MockAvatarWriterMockRecorder is the mock recorder for MockAvatarWriter.
type MockAvatarWriterMockRecorder struct {
	mock *MockAvatarWriter
}

// NewMockAvatarWriter creates a new mock instance.
func NewMockAvatarWriter(ctrl *gomock.Controller) *MockAvatarWriter {
	mock := &MockAvatarWriter{ctrl: ctrl}
	mock.recorder = &MockAvatarWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarWriter) EXPECT() *MockAvatarWriterMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAvatarWriter) Create(ctx context.Context, avatar *entity.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAvatarWriterMockRecorder) Create(ctx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAvatarWriter)(nil).Create), ctx, avatar)
}

// MarkUploadCompleted mocks base method.
func (m *MockAvatarWriter) MarkUploadCompleted(ctx context.Context, id string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUploadCompleted", ctx, id, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUploadCompleted indicates an expected call of MarkUploadCompleted.
func (mr *MockAvatarWriterMockRecorder) MarkUploadCompleted(ctx, id, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUploadCompleted", reflect.TypeOf((*MockAvatarWriter)(nil).MarkUploadCompleted), ctx, id, updatedAt)
}

// MarkUploadFailed mocks base method.
func (m *MockAvatarWriter) MarkUploadFailed(ctx context.Context, id string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUploadFailed", ctx, id, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUploadFailed indicates an expected call of MarkUploadFailed.
func (mr *MockAvatarWriterMockRecorder) MarkUploadFailed(ctx, id, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUploadFailed", reflect.TypeOf((*MockAvatarWriter)(nil).MarkUploadFailed), ctx, id, updatedAt)
}

// SoftDelete mocks base method.
func (m *MockAvatarWriter) SoftDelete(ctx context.Context, id, userID string, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAvatarWriterMockRecorder) SoftDelete(ctx, id, userID, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAvatarWriter)(nil).SoftDelete), ctx, id, userID, deletedAt)
}

// MockAvatarRepo is a mock of AvatarRepo interface.
type MockAvatarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepoMockRecorder
	isgomock struct{}
}

// MockAvatarRepoMockRecorder is the mock recorder for MockAvatarRepo.
type MockAvatarRepoMockRecorder struct {
	mock *MockAvatarRepo
}

// NewMockAvatarRepo creates a new mock instance.
func NewMockAvatarRepo(ctrl *gomock.Controller) *MockAvatarRepo {
	mock := &MockAvatarRepo{ctrl: ctrl}
	mock.recorder = &MockAvatarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepo) EXPECT() *MockAvatarRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAvatarRepo) Create(ctx context.Context, avatar *entity.Avatar) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, avatar)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAvatarRepoMockRecorder) Create(ctx, avatar any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAvatarRepo)(nil).Create), ctx, avatar)
}

// FindByID mocks base method.
func (m *MockAvatarRepo) FindByID(ctx context.Context, id string) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAvatarRepoMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAvatarRepo)(nil).FindByID), ctx, id)
}

// ListByUserID mocks base method.
func (m *MockAvatarRepo) ListByUserID(ctx context.Context, userID string) ([]entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAvatarRepoMockRecorder) ListByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAvatarRepo)(nil).ListByUserID), ctx, userID)
}

// ListExpiredUploading mocks base method.
func (m *MockAvatarRepo) ListExpiredUploading(ctx context.Context, before time.Time) ([]entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpiredUploading", ctx, before)
	ret0, _ := ret[0].([]entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpiredUploading indicates an expected call of ListExpiredUploading.
func (mr *MockAvatarRepoMockRecorder) ListExpiredUploading(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpiredUploading", reflect.TypeOf((*MockAvatarRepo)(nil).ListExpiredUploading), ctx, before)
}

// MarkUploadCompleted mocks base method.
func (m *MockAvatarRepo) MarkUploadCompleted(ctx context.Context, id string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUploadCompleted", ctx, id, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUploadCompleted indicates an expected call of MarkUploadCompleted.
func (mr *MockAvatarRepoMockRecorder) MarkUploadCompleted(ctx, id, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUploadCompleted", reflect.TypeOf((*MockAvatarRepo)(nil).MarkUploadCompleted), ctx, id, updatedAt)
}

// MarkUploadFailed mocks base method.
func (m *MockAvatarRepo) MarkUploadFailed(ctx context.Context, id string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkUploadFailed", ctx, id, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkUploadFailed indicates an expected call of MarkUploadFailed.
func (mr *MockAvatarRepoMockRecorder) MarkUploadFailed(ctx, id, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkUploadFailed", reflect.TypeOf((*MockAvatarRepo)(nil).MarkUploadFailed), ctx, id, updatedAt)
}

// Ping mocks base method.
func (m *MockAvatarRepo) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockAvatarRepoMockRecorder) Ping(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockAvatarRepo)(nil).Ping), ctx)
}

// SoftDelete mocks base method.
func (m *MockAvatarRepo) SoftDelete(ctx context.Context, id, userID string, deletedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id, userID, deletedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockAvatarRepoMockRecorder) SoftDelete(ctx, id, userID, deletedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockAvatarRepo)(nil).SoftDelete), ctx, id, userID, deletedAt)
}
