// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/server/avatar/application/port/outbox.go
//
// Generated by this command:
//
//	mockgen -source=app/internal/server/avatar/application/port/outbox.go -destination=app/internal/server/avatar/application/port/mocks/mock_outbox.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/iPatrushevSergey/gophprofile/app/internal/server/avatar/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockOutboxWriter is a mock of OutboxWriter interface.
type MockOutboxWriter struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxWriterMockRecorder
	isgomock struct{}
}

// MockOutboxWriterMockRecorder is the mock recorder for MockOutboxWriter.
type MockOutboxWriterMockRecorder struct {
	mock *MockOutboxWriter
}

// NewMockOutboxWriter creates a new mock instance.
func NewMockOutboxWriter(ctrl *gomock.Controller) *MockOutboxWriter {
	mock := &MockOutboxWriter{ctrl: ctrl}
	mock.recorder = &MockOutboxWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxWriter) EXPECT() *MockOutboxWriterMockRecorder {
	return m.recorder
}

// CreateDeleted mocks base method.
func (m *MockOutboxWriter) CreateDeleted(ctx context.Context, event dto.OutboxDeletedCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeleted indicates an expected call of CreateDeleted.
func (mr *MockOutboxWriterMockRecorder) CreateDeleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeleted", reflect.TypeOf((*MockOutboxWriter)(nil).CreateDeleted), ctx, event)
}

// CreateUploaded mocks base method.
func (m *MockOutboxWriter) CreateUploaded(ctx context.Context, event dto.OutboxUploadedCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUploaded", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUploaded indicates an expected call of CreateUploaded.
func (mr *MockOutboxWriterMockRecorder) CreateUploaded(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUploaded", reflect.TypeOf((*MockOutboxWriter)(nil).CreateUploaded), ctx, event)
}

// MarkPublished mocks base method.
func (m *MockOutboxWriter) MarkPublished(ctx context.Context, id string, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, id, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxWriterMockRecorder) MarkPublished(ctx, id, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxWriter)(nil).MarkPublished), ctx, id, publishedAt)
}

// ReleaseStalePublishing mocks base method.
func (m *MockOutboxWriter) ReleaseStalePublishing(ctx context.Context, publishingBefore time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseStalePublishing", ctx, publishingBefore)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseStalePublishing indicates an expected call of ReleaseStalePublishing.
func (mr *MockOutboxWriterMockRecorder) ReleaseStalePublishing(ctx, publishingBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStalePublishing", reflect.TypeOf((*MockOutboxWriter)(nil).ReleaseStalePublishing), ctx, publishingBefore)
}

// MockOutboxReader is a mock of OutboxReader interface.
type MockOutboxReader struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxReaderMockRecorder
	isgomock struct{}
}

// MockOutboxReaderMockRecorder is the mock recorder for MockOutboxReader.
type MockOutboxReaderMockRecorder struct {
	mock *MockOutboxReader
}

// NewMockOutboxReader creates a new mock instance.
func NewMockOutboxReader(ctrl *gomock.Controller) *MockOutboxReader {
	mock := &MockOutboxReader{ctrl: ctrl}
	mock.recorder = &MockOutboxReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxReader) EXPECT() *MockOutboxReaderMockRecorder {
	return m.recorder
}

// MarkPublishing mocks base method.
func (m *MockOutboxReader) MarkPublishing(ctx context.Context, limit int, publishingAt time.Time) ([]dto.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublishing", ctx, limit, publishingAt)
	ret0, _ := ret[0].([]dto.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPublishing indicates an expected call of MarkPublishing.
func (mr *MockOutboxReaderMockRecorder) MarkPublishing(ctx, limit, publishingAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublishing", reflect.TypeOf((*MockOutboxReader)(nil).MarkPublishing), ctx, limit, publishingAt)
}

// MockOutboxRepo is a mock of OutboxRepo interface.
type MockOutboxRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxRepoMockRecorder
	isgomock struct{}
}

// MockOutboxRepoMockRecorder is the mock recorder for MockOutboxRepo.
type MockOutboxRepoMockRecorder struct {
	mock *MockOutboxRepo
}

// NewMockOutboxRepo creates a new mock instance.
func NewMockOutboxRepo(ctrl *gomock.Controller) *MockOutboxRepo {
	mock := &MockOutboxRepo{ctrl: ctrl}
	mock.recorder = &MockOutboxRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxRepo) EXPECT() *MockOutboxRepoMockRecorder {
	return m.recorder
}

// CreateDeleted mocks base method.
func (m *MockOutboxRepo) CreateDeleted(ctx context.Context, event dto.OutboxDeletedCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeleted", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeleted indicates an expected call of CreateDeleted.
func (mr *MockOutboxRepoMockRecorder) CreateDeleted(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeleted", reflect.TypeOf((*MockOutboxRepo)(nil).CreateDeleted), ctx, event)
}

// CreateUploaded mocks base method.
func (m *MockOutboxRepo) CreateUploaded(ctx context.Context, event dto.OutboxUploadedCreate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUploaded", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateUploaded indicates an expected call of CreateUploaded.
func (mr *MockOutboxRepoMockRecorder) CreateUploaded(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUploaded", reflect.TypeOf((*MockOutboxRepo)(nil).CreateUploaded), ctx, event)
}

// MarkPublished mocks base method.
func (m *MockOutboxRepo) MarkPublished(ctx context.Context, id string, publishedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublished", ctx, id, publishedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkPublished indicates an expected call of MarkPublished.
func (mr *MockOutboxRepoMockRecorder) MarkPublished(ctx, id, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublished", reflect.TypeOf((*MockOutboxRepo)(nil).MarkPublished), ctx, id, publishedAt)
}

// MarkPublishing mocks base method.
func (m *MockOutboxRepo) MarkPublishing(ctx context.Context, limit int, publishingAt time.Time) ([]dto.OutboxEvent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkPublishing", ctx, limit, publishingAt)
	ret0, _ := ret[0].([]dto.OutboxEvent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarkPublishing indicates an expected call of MarkPublishing.
func (mr *MockOutboxRepoMockRecorder) MarkPublishing(ctx, limit, publishingAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkPublishing", reflect.TypeOf((*MockOutboxRepo)(nil).MarkPublishing), ctx, limit, publishingAt)
}

// ReleaseStalePublishing mocks base method.
func (m *MockOutboxRepo) ReleaseStalePublishing(ctx context.Context, publishingBefore time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseStalePublishing", ctx, publishingBefore)
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseStalePublishing indicates an expected call of ReleaseStalePublishing.
func (mr *MockOutboxRepoMockRecorder) ReleaseStalePublishing(ctx, publishingBefore any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseStalePublishing", reflect.TypeOf((*MockOutboxRepo)(nil).ReleaseStalePublishing), ctx, publishingBefore)
}
