// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonF642ad3eDecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel(in *jlexer.Lexer, out *AvatarUploadedEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avatar_id":
			out.AvatarID = string(in.String())
		case "user_id":
			out.UserID = string(in.String())
		case "s3_key":
			out.S3Key = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF642ad3eEncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel(out *jwriter.Writer, in AvatarUploadedEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.AvatarID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"s3_key\":"
		out.RawString(prefix)
		out.String(string(in.S3Key))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AvatarUploadedEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF642ad3eEncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AvatarUploadedEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF642ad3eEncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AvatarUploadedEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF642ad3eDecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AvatarUploadedEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF642ad3eDecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel(l, v)
}
func easyjsonF642ad3eDecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel1(in *jlexer.Lexer, out *AvatarDeletedEvent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "avatar_id":
			out.AvatarID = string(in.String())
		case "s3_keys":
			if in.IsNull() {
				in.Skip()
				out.S3Keys = nil
			} else {
				in.Delim('[')
				if out.S3Keys == nil {
					if !in.IsDelim(']') {
						out.S3Keys = make([]string, 0, 4)
					} else {
						out.S3Keys = []string{}
					}
				} else {
					out.S3Keys = (out.S3Keys)[:0]
				}
				for !in.IsDelim(']') {
					var v1 string
					v1 = string(in.String())
					out.S3Keys = append(out.S3Keys, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonF642ad3eEncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel1(out *jwriter.Writer, in AvatarDeletedEvent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"avatar_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.AvatarID))
	}
	{
		const prefix string = ",\"s3_keys\":"
		out.RawString(prefix)
		if in.S3Keys == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.S3Keys {
				if v2 > 0 {
					out.RawByte(',')
				}
				out.String(string(v3))
			}
			out.RawByte(']')
		}
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AvatarDeletedEvent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonF642ad3eEncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AvatarDeletedEvent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonF642ad3eEncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AvatarDeletedEvent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonF642ad3eDecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AvatarDeletedEvent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonF642ad3eDecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarAdaptersRepositoryRabbitmqModel1(l, v)
}
