// Code generated by MockGen. DO NOT EDIT.
// Source: metrics.go
//
// Generated by this command:
//
//	mockgen -source=metrics.go -destination=mocks/mock_metrics.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	port "github.com/iPatrushevSergey/gophprofile/app/internal/pkg/port"
	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// ObserveDBPool mocks base method.
func (m *MockMetrics) ObserveDBPool(ctx context.Context, stats port.DBPoolStats) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveDBPool", ctx, stats)
}

// ObserveDBPool indicates an expected call of ObserveDBPool.
func (mr *MockMetricsMockRecorder) ObserveDBPool(ctx, stats any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveDBPool", reflect.TypeOf((*MockMetrics)(nil).ObserveDBPool), ctx, stats)
}

// RecordDelete mocks base method.
func (m *MockMetrics) RecordDelete(ctx context.Context, status string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordDelete", ctx, status)
}

// RecordDelete indicates an expected call of RecordDelete.
func (mr *MockMetricsMockRecorder) RecordDelete(ctx, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordDelete", reflect.TypeOf((*MockMetrics)(nil).RecordDelete), ctx, status)
}

// RecordHTTPRequest mocks base method.
func (m *MockMetrics) RecordHTTPRequest(ctx context.Context, method, route, statusClass string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordHTTPRequest", ctx, method, route, statusClass, duration)
}

// RecordHTTPRequest indicates an expected call of RecordHTTPRequest.
func (mr *MockMetricsMockRecorder) RecordHTTPRequest(ctx, method, route, statusClass, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordHTTPRequest", reflect.TypeOf((*MockMetrics)(nil).RecordHTTPRequest), ctx, method, route, statusClass, duration)
}

// RecordProcessing mocks base method.
func (m *MockMetrics) RecordProcessing(ctx context.Context, status string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordProcessing", ctx, status, duration)
}

// RecordProcessing indicates an expected call of RecordProcessing.
func (mr *MockMetricsMockRecorder) RecordProcessing(ctx, status, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordProcessing", reflect.TypeOf((*MockMetrics)(nil).RecordProcessing), ctx, status, duration)
}

// RecordUpload mocks base method.
func (m *MockMetrics) RecordUpload(ctx context.Context, status string, duration time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecordUpload", ctx, status, duration)
}

// RecordUpload indicates an expected call of RecordUpload.
func (mr *MockMetricsMockRecorder) RecordUpload(ctx, status, duration any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordUpload", reflect.TypeOf((*MockMetrics)(nil).RecordUpload), ctx, status, duration)
}

// SetOutboxPending mocks base method.
func (m *MockMetrics) SetOutboxPending(ctx context.Context, count int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOutboxPending", ctx, count)
}

// SetOutboxPending indicates an expected call of SetOutboxPending.
func (mr *MockMetricsMockRecorder) SetOutboxPending(ctx, count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOutboxPending", reflect.TypeOf((*MockMetrics)(nil).SetOutboxPending), ctx, count)
}

// SetStorageBytes mocks base method.
func (m *MockMetrics) SetStorageBytes(ctx context.Context, bytes int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStorageBytes", ctx, bytes)
}

// SetStorageBytes indicates an expected call of SetStorageBytes.
func (mr *MockMetricsMockRecorder) SetStorageBytes(ctx, bytes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStorageBytes", reflect.TypeOf((*MockMetrics)(nil).SetStorageBytes), ctx, bytes)
}
