// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/pkg/port/tracing.go
//
// Generated by this command:
//
//	mockgen -source=app/internal/pkg/port/tracing.go -destination=app/internal/pkg/port/mocks/mock_tracer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	port "github.com/iPatrushevSergey/gophprofile/app/internal/pkg/port"
	gomock "go.uber.org/mock/gomock"
)

// MockTracer is a mock of Tracer interface.
type MockTracer struct {
	ctrl     *gomock.Controller
	recorder *MockTracerMockRecorder
	isgomock struct{}
}

// MockTracerMockRecorder is the mock recorder for MockTracer.
type MockTracerMockRecorder struct {
	mock *MockTracer
}

// NewMockTracer creates a new mock instance.
func NewMockTracer(ctrl *gomock.Controller) *MockTracer {
	mock := &MockTracer{ctrl: ctrl}
	mock.recorder = &MockTracerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTracer) EXPECT() *MockTracerMockRecorder {
	return m.recorder
}

// ContextToMap mocks base method.
func (m *MockTracer) ContextToMap(ctx context.Context) map[string]string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ContextToMap", ctx)
	ret0, _ := ret[0].(map[string]string)
	return ret0
}

// ContextToMap indicates an expected call of ContextToMap.
func (mr *MockTracerMockRecorder) ContextToMap(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ContextToMap", reflect.TypeOf((*MockTracer)(nil).ContextToMap), ctx)
}

// MapToContext mocks base method.
func (m *MockTracer) MapToContext(ctx context.Context, carrier map[string]string) context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MapToContext", ctx, carrier)
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// MapToContext indicates an expected call of MapToContext.
func (mr *MockTracerMockRecorder) MapToContext(ctx, carrier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MapToContext", reflect.TypeOf((*MockTracer)(nil).MapToContext), ctx, carrier)
}

// Start mocks base method.
func (m *MockTracer) Start(ctx context.Context, config port.SpanConfig) (context.Context, port.Span) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, config)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(port.Span)
	return ret0, ret1
}

// Start indicates an expected call of Start.
func (mr *MockTracerMockRecorder) Start(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTracer)(nil).Start), ctx, config)
}

// MockSpan is a mock of Span interface.
type MockSpan struct {
	ctrl     *gomock.Controller
	recorder *MockSpanMockRecorder
	isgomock struct{}
}

// MockSpanMockRecorder is the mock recorder for MockSpan.
type MockSpanMockRecorder struct {
	mock *MockSpan
}

// NewMockSpan creates a new mock instance.
func NewMockSpan(ctrl *gomock.Controller) *MockSpan {
	mock := &MockSpan{ctrl: ctrl}
	mock.recorder = &MockSpanMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSpan) EXPECT() *MockSpanMockRecorder {
	return m.recorder
}

// AddAttributes mocks base method.
func (m *MockSpan) AddAttributes(attrs ...port.Attribute) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range attrs {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "AddAttributes", varargs...)
}

// AddAttributes indicates an expected call of AddAttributes.
func (mr *MockSpanMockRecorder) AddAttributes(attrs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAttributes", reflect.TypeOf((*MockSpan)(nil).AddAttributes), attrs...)
}

// End mocks base method.
func (m *MockSpan) End() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "End")
}

// End indicates an expected call of End.
func (mr *MockSpanMockRecorder) End() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "End", reflect.TypeOf((*MockSpan)(nil).End))
}

// Fail mocks base method.
func (m *MockSpan) Fail(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Fail", err)
}

// Fail indicates an expected call of Fail.
func (mr *MockSpanMockRecorder) Fail(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fail", reflect.TypeOf((*MockSpan)(nil).Fail), err)
}
