{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gophprofile.fullname" . }}-app
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "gophprofile.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
type: Opaque
stringData:
  GOPHPROFILE_DATABASE_URI: {{ include "gophprofile.databaseURI" . | quote }}
  GOPHPROFILE_BROKER_URL: {{ include "gophprofile.brokerURL" . | quote }}
  GOPHPROFILE_MINIO_ACCESS_KEY: {{ .Values.minio.rootUser | quote }}
  GOPHPROFILE_MINIO_SECRET_KEY: {{ .Values.minio.rootPassword | quote }}
{{- end }}
