// Code generated by github.com/jmattheis/goverter, DO NOT EDIT.
//go:build !goverter

package converter

import (
	convext "github.com/iPatrushevSergey/gophprofile/app/internal/server/avatar/adapters/repository/postgres/converter/convext"
	model "github.com/iPatrushevSergey/gophprofile/app/internal/server/avatar/adapters/repository/postgres/model"
	entity "github.com/iPatrushevSergey/gophprofile/app/internal/server/avatar/domain/entity"
)

type AvatarConverterImpl struct{}

func (c *AvatarConverterImpl) ToEntity(source model.Avatar) (entity.Avatar, error) {
	var entityAvatar entity.Avatar
	entityAvatar.ID = convext.UUIDToString(source.ID)
	entityAvatar.UserID = source.UserID
	entityAvatar.FileName = source.FileName
	entityAvatar.MimeType = source.MimeType
	entityAvatar.SizeBytes = source.SizeBytes
	entityAvatar.S3Key = source.S3Key
	thumbnailS3Keys, err := convext.RawMessageToThumbnailS3Keys(source.ThumbnailS3Keys)
	if err != nil {
		return entityAvatar, err
	}
	entityAvatar.ThumbnailS3Keys = thumbnailS3Keys
	entityAvatar.UploadStatus = convext.StringToUploadStatus(source.UploadStatus)
	entityAvatar.ProcessingStatus = convext.StringToProcessingStatus(source.ProcessingStatus)
	entityAvatar.CreatedAt = convext.CopyTime(source.CreatedAt)
	entityAvatar.UpdatedAt = convext.CopyTime(source.UpdatedAt)
	entityAvatar.DeletedAt = convext.CopyTimePtr(source.DeletedAt)
	return entityAvatar, nil
}

func (c *AvatarConverterImpl) ToModel(source entity.Avatar) (model.Avatar, error) {
	var modelAvatar model.Avatar
	uuidID, err := convext.StringToUUID(source.ID)
	if err != nil {
		return modelAvatar, err
	}
	modelAvatar.ID = uuidID
	modelAvatar.UserID = source.UserID
	modelAvatar.FileName = source.FileName
	modelAvatar.MimeType = source.MimeType
	modelAvatar.SizeBytes = source.SizeBytes
	modelAvatar.S3Key = source.S3Key
	thumbnailS3Keys, err := convext.ThumbnailS3KeysToRawMessage(source.ThumbnailS3Keys)
	if err != nil {
		return modelAvatar, err
	}
	modelAvatar.ThumbnailS3Keys = thumbnailS3Keys
	modelAvatar.UploadStatus = convext.UploadStatusToString(source.UploadStatus)
	modelAvatar.ProcessingStatus = convext.ProcessingStatusToString(source.ProcessingStatus)
	modelAvatar.CreatedAt = convext.CopyTime(source.CreatedAt)
	modelAvatar.UpdatedAt = convext.CopyTime(source.UpdatedAt)
	modelAvatar.DeletedAt = convext.CopyTimePtr(source.DeletedAt)
	return modelAvatar, nil
}
