// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package dto

import (
	json "encoding/json"

	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto(in *jlexer.Lexer, out *UploadAvatarResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "user_id":
			out.UserID = string(in.String())
		case "url":
			out.URL = string(in.String())
		case "status":
			out.Status = string(in.String())
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto(out *jwriter.Writer, in UploadAvatarResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix)
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UploadAvatarResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UploadAvatarResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UploadAvatarResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UploadAvatarResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto(l, v)
}
func easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto1(in *jlexer.Lexer, out *UploadAvatarRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "FileName":
			out.FileName = string(in.String())
		case "MimeType":
			out.MimeType = string(in.String())
		case "Content":
			if in.IsNull() {
				in.Skip()
				out.Content = nil
			} else {
				out.Content = in.Bytes()
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto1(out *jwriter.Writer, in UploadAvatarRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"FileName\":"
		out.RawString(prefix[1:])
		out.String(string(in.FileName))
	}
	{
		const prefix string = ",\"MimeType\":"
		out.RawString(prefix)
		out.String(string(in.MimeType))
	}
	{
		const prefix string = ",\"Content\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Content)
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v UploadAvatarRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v UploadAvatarRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *UploadAvatarRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *UploadAvatarRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto1(l, v)
}
func easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto2(in *jlexer.Lexer, out *ThumbnailURL) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "size":
			out.Size = string(in.String())
		case "url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto2(out *jwriter.Writer, in ThumbnailURL) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"size\":"
		out.RawString(prefix[1:])
		out.String(string(in.Size))
	}
	{
		const prefix string = ",\"url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ThumbnailURL) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ThumbnailURL) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ThumbnailURL) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ThumbnailURL) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto2(l, v)
}
func easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto3(in *jlexer.Lexer, out *HealthResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "status":
			out.Status = string(in.String())
		case "database":
			out.Database = string(in.String())
		case "storage":
			out.Storage = string(in.String())
		case "broker":
			out.Broker = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto3(out *jwriter.Writer, in HealthResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"status\":"
		out.RawString(prefix[1:])
		out.String(string(in.Status))
	}
	{
		const prefix string = ",\"database\":"
		out.RawString(prefix)
		out.String(string(in.Database))
	}
	{
		const prefix string = ",\"storage\":"
		out.RawString(prefix)
		out.String(string(in.Storage))
	}
	{
		const prefix string = ",\"broker\":"
		out.RawString(prefix)
		out.String(string(in.Broker))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v HealthResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v HealthResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *HealthResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *HealthResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto3(l, v)
}
func easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto4(in *jlexer.Lexer, out *ErrorResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "error":
			out.Error = string(in.String())
		case "details":
			out.Details = string(in.String())
		case "max_size":
			out.MaxSize = int64(in.Int64())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto4(out *jwriter.Writer, in ErrorResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"error\":"
		out.RawString(prefix[1:])
		out.String(string(in.Error))
	}
	if in.Details != "" {
		const prefix string = ",\"details\":"
		out.RawString(prefix)
		out.String(string(in.Details))
	}
	if in.MaxSize != 0 {
		const prefix string = ",\"max_size\":"
		out.RawString(prefix)
		out.Int64(int64(in.MaxSize))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ErrorResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto4(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ErrorResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto4(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ErrorResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto4(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ErrorResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto4(l, v)
}
func easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto5(in *jlexer.Lexer, out *AvatarMetadataResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = string(in.String())
		case "user_id":
			out.UserID = string(in.String())
		case "file_name":
			out.FileName = string(in.String())
		case "mime_type":
			out.MimeType = string(in.String())
		case "size_bytes":
			out.SizeBytes = int64(in.Int64())
		case "thumbnails":
			if in.IsNull() {
				in.Skip()
				out.Thumbnails = nil
			} else {
				in.Delim('[')
				if out.Thumbnails == nil {
					if !in.IsDelim(']') {
						out.Thumbnails = make([]ThumbnailURL, 0, 2)
					} else {
						out.Thumbnails = []ThumbnailURL{}
					}
				} else {
					out.Thumbnails = (out.Thumbnails)[:0]
				}
				for !in.IsDelim(']') {
					var v4 ThumbnailURL
					(v4).UnmarshalEasyJSON(in)
					out.Thumbnails = append(out.Thumbnails, v4)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "created_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.CreatedAt).UnmarshalJSON(data))
			}
		case "updated_at":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.UpdatedAt).UnmarshalJSON(data))
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto5(out *jwriter.Writer, in AvatarMetadataResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"user_id\":"
		out.RawString(prefix)
		out.String(string(in.UserID))
	}
	{
		const prefix string = ",\"file_name\":"
		out.RawString(prefix)
		out.String(string(in.FileName))
	}
	{
		const prefix string = ",\"mime_type\":"
		out.RawString(prefix)
		out.String(string(in.MimeType))
	}
	{
		const prefix string = ",\"size_bytes\":"
		out.RawString(prefix)
		out.Int64(int64(in.SizeBytes))
	}
	{
		const prefix string = ",\"thumbnails\":"
		out.RawString(prefix)
		if in.Thumbnails == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v5, v6 := range in.Thumbnails {
				if v5 > 0 {
					out.RawByte(',')
				}
				(v6).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	{
		const prefix string = ",\"created_at\":"
		out.RawString(prefix)
		out.Raw((in.CreatedAt).MarshalJSON())
	}
	{
		const prefix string = ",\"updated_at\":"
		out.RawString(prefix)
		out.Raw((in.UpdatedAt).MarshalJSON())
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v AvatarMetadataResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto5(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v AvatarMetadataResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson97d7cd47EncodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto5(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *AvatarMetadataResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto5(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *AvatarMetadataResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson97d7cd47DecodeGithubComIPatrushevSergeyGophprofileAppInternalServerAvatarPresentationHttpDto5(l, v)
}
