// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/processor/processing/application/port/image_resizer.go
//
// Generated by this command:
//
//	mockgen -source=app/internal/processor/processing/application/port/image_resizer.go -destination=app/internal/processor/processing/application/port/mocks/mock_image_resizer.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockImageResizer is a mock of ImageResizer interface.
type MockImageResizer struct {
	ctrl     *gomock.Controller
	recorder *MockImageResizerMockRecorder
	isgomock struct{}
}

// MockImageResizerMockRecorder is the mock recorder for MockImageResizer.
type MockImageResizerMockRecorder struct {
	mock *MockImageResizer
}

// NewMockImageResizer creates a new mock instance.
func NewMockImageResizer(ctrl *gomock.Controller) *MockImageResizer {
	mock := &MockImageResizer{ctrl: ctrl}
	mock.recorder = &MockImageResizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageResizer) EXPECT() *MockImageResizerMockRecorder {
	return m.recorder
}

// Dimensions mocks base method.
func (m *MockImageResizer) Dimensions(data []byte) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dimensions", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Dimensions indicates an expected call of Dimensions.
func (mr *MockImageResizerMockRecorder) Dimensions(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dimensions", reflect.TypeOf((*MockImageResizer)(nil).Dimensions), data)
}

// Resize mocks base method.
func (m *MockImageResizer) Resize(ctx context.Context, data []byte, width, height int) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", ctx, data, width, height)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resize indicates an expected call of Resize.
func (mr *MockImageResizerMockRecorder) Resize(ctx, data, width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockImageResizer)(nil).Resize), ctx, data, width, height)
}
