// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/processor/processing/application/port/file_repository.go
//
// Generated by this command:
//
//	mockgen -source=app/internal/processor/processing/application/port/file_repository.go -destination=app/internal/processor/processing/application/port/mocks/mock_file_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockFileRepo is a mock of FileRepo interface.
type MockFileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockFileRepoMockRecorder
	isgomock struct{}
}

// MockFileRepoMockRecorder is the mock recorder for MockFileRepo.
type MockFileRepoMockRecorder struct {
	mock *MockFileRepo
}

// NewMockFileRepo creates a new mock instance.
func NewMockFileRepo(ctrl *gomock.Controller) *MockFileRepo {
	mock := &MockFileRepo{ctrl: ctrl}
	mock.recorder = &MockFileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFileRepo) EXPECT() *MockFileRepoMockRecorder {
	return m.recorder
}

// MarkAlive mocks base method.
func (m *MockFileRepo) MarkAlive(ctx context.Context, path string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAlive", ctx, path)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAlive indicates an expected call of MarkAlive.
func (mr *MockFileRepoMockRecorder) MarkAlive(ctx, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAlive", reflect.TypeOf((*MockFileRepo)(nil).MarkAlive), ctx, path)
}
