// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/processor/processing/application/port/image_processor.go
//
// Generated by this command:
//
//	mockgen -source=app/internal/processor/processing/application/port/image_processor.go -destination=app/internal/processor/processing/application/port/mocks/mock_image_processor.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	image "image"
	reflect "reflect"

	vo "github.com/iPatrushevSergey/gophprofile/app/internal/processor/processing/domain/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockImageProcessor is a mock of ImageProcessor interface.
type MockImageProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockImageProcessorMockRecorder
	isgomock struct{}
}

// MockImageProcessorMockRecorder is the mock recorder for MockImageProcessor.
type MockImageProcessorMockRecorder struct {
	mock *MockImageProcessor
}

// NewMockImageProcessor creates a new mock instance.
func NewMockImageProcessor(ctrl *gomock.Controller) *MockImageProcessor {
	mock := &MockImageProcessor{ctrl: ctrl}
	mock.recorder = &MockImageProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockImageProcessor) EXPECT() *MockImageProcessorMockRecorder {
	return m.recorder
}

// Dimensions mocks base method.
func (m *MockImageProcessor) Dimensions(data []byte) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dimensions", data)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Dimensions indicates an expected call of Dimensions.
func (mr *MockImageProcessorMockRecorder) Dimensions(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dimensions", reflect.TypeOf((*MockImageProcessor)(nil).Dimensions), data)
}

// Encode mocks base method.
func (m *MockImageProcessor) Encode(src image.Image, format vo.OutputFormat) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encode", src, format)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Encode indicates an expected call of Encode.
func (mr *MockImageProcessorMockRecorder) Encode(src, format any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encode", reflect.TypeOf((*MockImageProcessor)(nil).Encode), src, format)
}

// Resize mocks base method.
func (m *MockImageProcessor) Resize(data []byte, width, height int) (image.Image, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resize", data, width, height)
	ret0, _ := ret[0].(image.Image)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resize indicates an expected call of Resize.
func (mr *MockImageProcessorMockRecorder) Resize(data, width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resize", reflect.TypeOf((*MockImageProcessor)(nil).Resize), data, width, height)
}
