// Code generated by MockGen. DO NOT EDIT.
// Source: app/internal/processor/processing/application/port/avatar_repository.go
//
// Generated by this command:
//
//	mockgen -source=app/internal/processor/processing/application/port/avatar_repository.go -destination=app/internal/processor/processing/application/port/mocks/mock_avatar_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	dto "github.com/iPatrushevSergey/gophprofile/app/internal/processor/processing/application/dto"
	entity "github.com/iPatrushevSergey/gophprofile/app/internal/processor/processing/domain/entity"
	vo "github.com/iPatrushevSergey/gophprofile/app/internal/processor/processing/domain/vo"
	gomock "go.uber.org/mock/gomock"
)

// MockAvatarReader is a mock of AvatarReader interface.
type MockAvatarReader struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarReaderMockRecorder
	isgomock struct{}
}

// MockAvatarReaderMockRecorder is the mock recorder for MockAvatarReader.
type MockAvatarReaderMockRecorder struct {
	mock *MockAvatarReader
}

// NewMockAvatarReader creates a new mock instance.
func NewMockAvatarReader(ctrl *gomock.Controller) *MockAvatarReader {
	mock := &MockAvatarReader{ctrl: ctrl}
	mock.recorder = &MockAvatarReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarReader) EXPECT() *MockAvatarReaderMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockAvatarReader) FindByID(ctx context.Context, id string) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAvatarReaderMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAvatarReader)(nil).FindByID), ctx, id)
}

// MockAvatarWriter is a mock of AvatarWriter interface.
type MockAvatarWriter struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarWriterMockRecorder
	isgomock struct{}
}

// MockAvatarWriterMockRecorder is the mock recorder for MockAvatarWriter.
type MockAvatarWriterMockRecorder struct {
	mock *MockAvatarWriter
}

// NewMockAvatarWriter creates a new mock instance.
func NewMockAvatarWriter(ctrl *gomock.Controller) *MockAvatarWriter {
	mock := &MockAvatarWriter{ctrl: ctrl}
	mock.recorder = &MockAvatarWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarWriter) EXPECT() *MockAvatarWriterMockRecorder {
	return m.recorder
}

// CompleteProcessing mocks base method.
func (m *MockAvatarWriter) CompleteProcessing(ctx context.Context, in dto.CompleteProcessingInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteProcessing", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteProcessing indicates an expected call of CompleteProcessing.
func (mr *MockAvatarWriterMockRecorder) CompleteProcessing(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteProcessing", reflect.TypeOf((*MockAvatarWriter)(nil).CompleteProcessing), ctx, in)
}

// StartProcessing mocks base method.
func (m *MockAvatarWriter) StartProcessing(ctx context.Context, id string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartProcessing", ctx, id, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartProcessing indicates an expected call of StartProcessing.
func (mr *MockAvatarWriterMockRecorder) StartProcessing(ctx, id, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcessing", reflect.TypeOf((*MockAvatarWriter)(nil).StartProcessing), ctx, id, updatedAt)
}

// UpdateProcessingStatus mocks base method.
func (m *MockAvatarWriter) UpdateProcessingStatus(ctx context.Context, id string, status vo.ProcessingStatus, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", ctx, id, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockAvatarWriterMockRecorder) UpdateProcessingStatus(ctx, id, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockAvatarWriter)(nil).UpdateProcessingStatus), ctx, id, status, updatedAt)
}

// MockAvatarRepo is a mock of AvatarRepo interface.
type MockAvatarRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarRepoMockRecorder
	isgomock struct{}
}

// MockAvatarRepoMockRecorder is the mock recorder for MockAvatarRepo.
type MockAvatarRepoMockRecorder struct {
	mock *MockAvatarRepo
}

// NewMockAvatarRepo creates a new mock instance.
func NewMockAvatarRepo(ctrl *gomock.Controller) *MockAvatarRepo {
	mock := &MockAvatarRepo{ctrl: ctrl}
	mock.recorder = &MockAvatarRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarRepo) EXPECT() *MockAvatarRepoMockRecorder {
	return m.recorder
}

// CompleteProcessing mocks base method.
func (m *MockAvatarRepo) CompleteProcessing(ctx context.Context, in dto.CompleteProcessingInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteProcessing", ctx, in)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteProcessing indicates an expected call of CompleteProcessing.
func (mr *MockAvatarRepoMockRecorder) CompleteProcessing(ctx, in any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteProcessing", reflect.TypeOf((*MockAvatarRepo)(nil).CompleteProcessing), ctx, in)
}

// FindByID mocks base method.
func (m *MockAvatarRepo) FindByID(ctx context.Context, id string) (*entity.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockAvatarRepoMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockAvatarRepo)(nil).FindByID), ctx, id)
}

// StartProcessing mocks base method.
func (m *MockAvatarRepo) StartProcessing(ctx context.Context, id string, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StartProcessing", ctx, id, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// StartProcessing indicates an expected call of StartProcessing.
func (mr *MockAvatarRepoMockRecorder) StartProcessing(ctx, id, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StartProcessing", reflect.TypeOf((*MockAvatarRepo)(nil).StartProcessing), ctx, id, updatedAt)
}

// UpdateProcessingStatus mocks base method.
func (m *MockAvatarRepo) UpdateProcessingStatus(ctx context.Context, id string, status vo.ProcessingStatus, updatedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProcessingStatus", ctx, id, status, updatedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProcessingStatus indicates an expected call of UpdateProcessingStatus.
func (mr *MockAvatarRepoMockRecorder) UpdateProcessingStatus(ctx, id, status, updatedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProcessingStatus", reflect.TypeOf((*MockAvatarRepo)(nil).UpdateProcessingStatus), ctx, id, status, updatedAt)
}
